# Generated by Django 2.1.5 on 2019-03-13 13:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Number must be of 10 digits, starting with either 6,7,8 or 9 with no prefix(+91 or 0)', regex='^[9876]\\d{9}$')])),
                ('name', models.CharField(blank=True, default='Mastrooms User', max_length=124)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_owner', models.BooleanField(default=True, verbose_name='Owner')),
                ('is_tenant', models.BooleanField(default=False, verbose_name='Tenant')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=24)),
                ('address', models.CharField(choices=[('Army Area', 'Army Area'), ('AnantPura', 'AnantPura'), ('Bajrang Nagar', 'Bajrang Nagar'), ('Ballabh Nagar', 'Ballabh Nagar'), ('Borkhera', 'Borkhera'), ('Bhimganj Mandi', 'Bhimganj Mandi'), ('Chawani', 'Chawani'), ('Dadawadi', 'Dadawadi'), ('Dhanmandi', 'Dhanmandi'), ('Ganesh Nagar', 'Ganesh Nagar'), ('Girdharpura', 'Girdharpura'), ('Gordhanpura', 'Gordhanpura'), ('Gumanpura', 'Gumanpura'), ('Indra Vihar', 'Indra Vihar'), ('JK Colony', 'JK Colony'), ('Keshav Pura', 'Keshav Pura'), ('Kunhari', 'Kunhari'), ('Mahavir Nagar Ist', 'Mahavir Nagar Ist'), ('Mahavir Nagar IInd', 'Mahavir Nagar IInd'), ('Mahavir Nagar IIIrd', 'Mahavir Nagar IIIrd'), ('Mokhapura', 'Mokhapura'), ('NayaPura', 'NayaPura'), ('Narcotics Colony', 'Narcotics Colony'), ('Rajeev Gandhi Nagar', 'Rajeev Gandhi Nagar'), ('Old Rajeev Gandhi Nagar', 'Old Rajeev Gandhi Nagar'), ('Parijat Colony', 'Parijat Colony'), ('Poonam Colony', 'Poonam Colony'), ('Prem Nagar', 'Prem Nagar'), ('Ramganj Mandi', 'Ramganj Mandi'), ('Rampura', 'Rampura'), ('Rangbari', 'Rangbari'), ('R.K Puram', 'R.K Puram'), ('Sanjay Nagar', 'Sanjay Nagar'), ('Shivpura', 'Shivpura'), ('Shubhash Nagar', 'Shubhash Nagar'), ('Srinath Puram', 'Srinath Puram'), ('Swami Vivekanand Nagar', 'Swami Vivekanand Nagar'), ('Talwandi', 'Talwandi'), ('Transport Nagar', 'Transport Nagar'), ('Vigyan Nagar', 'Vigyan Nagar'), ('Other', 'Other')], max_length=50)),
                ('category', models.CharField(choices=[("Boys' Hostel", "Boys' Hostel"), ("Boys' PG", "Boys' PG"), ("Girls' Hostel", "Girl's Hostel"), ("Girls' PG", "Girl's PG"), ('Family Room', 'Family Room'), ('Flats', 'Flats')], max_length=13)),
                ('occupancy', models.CharField(choices=[('Single', 'Single Seater'), ('Double', 'Double Seater'), ('Dormitory', 'Dormitory')], default='Single', max_length=9)),
                ('landmark', models.CharField(blank='True', max_length=124)),
                ('rent', models.PositiveIntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='mastrooms/static/media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='mastrooms/static/media')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='mastrooms/static/media')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='mastrooms/static/media')),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('other_amenities', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('other_contact_number', models.TextField(blank=True)),
                ('phone_number', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('room_key', models.CharField(blank=True, editable='False', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number_of_rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('coaching', models.CharField(choices=[('Aakash', 'Aakash Institute'), ('Allen', 'ALLEN Career Institute'), ('Bansal', 'Bansal Classes'), ('Career Point', 'Career Point'), ('Motion', 'Motion Education'), ('Nucleus', 'Nucleus Education'), ('Rao', 'RaoIIT'), ('Reso', 'Resonance'), ('Sarvottam', 'Sarvottam'), ('Vibrant', 'Vibrant'), ('Other', 'Other')], default='Kota Coaching', max_length=50)),
                ('home_address', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mastrooms.Room')),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastrooms.Owner'),
        ),
    ]
