# Generated by Django 2.1.5 on 2019-04-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastrooms', '0002_auto_20190410_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='elevator',
            new_name='mess',
        ),
        migrations.RemoveField(
            model_name='room',
            name='table_chair',
        ),
        migrations.AddField(
            model_name='room',
            name='chair_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='fan',
            field=models.BooleanField(default=True),
        ),
    ]
