# Generated by Django 2.1.5 on 2019-04-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrooms', '0003_auto_20190410_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bucket_mug',
            new_name='bucket',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='chair_table',
            new_name='table',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cooler',
        ),
    ]
