# Generated by Django 2.1.5 on 2019-04-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrooms', '0005_auto_20190410_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='mattress',
        ),
    ]
