# Generated by Django 2.1.5 on 2019-04-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastrooms', '0006_auto_20190411_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
