# Generated by Django 2.1.5 on 2019-04-11 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastrooms', '0007_auto_20190411_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.CharField(default=9123456789, max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', regex='^[9876]\\d{9}$')]),
            preserve_default=False,
        ),
    ]
