# Generated by Django 2.1.5 on 2019-04-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastrooms', '0008_auto_20190411_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
